name: Create Release and Upload MCPB

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: MCP Football API ${{ github.event.inputs.version }}
          body: |
            MCP Bundle release for Football API server

            ## Installation

            Download the `.mcpb` file and use it with your MCP client.

            ## Usage

            ```bash
            mcp-client install https://github.com/basriayaz/mcp-football-api/releases/download/${{ github.event.inputs.version }}/mcp-football-api-${{ github.event.inputs.version }}.mcpb
            ```
          draft: false
          prerelease: false